# 路由分组
Route:
  Prefix: "admin-api"
  Middleware: "lakego-admin"
  AdminMiddleware: "lakego-admin-check"

# 文件上传
Upload:
  # Disk in `config/filesystem.yml`.
  Disk: "public"

  # 格式化文件名类型： unique, datetime or sequence, 默认为空使用原始名称
  Formatname: "unique"

  # 上传文件 key
  Field: "file"

  # 目录
  Directory:
    Image: "images"
    Media: "medias"
    File: "files"

  # 文件类型
  Filetypes:
    Image: "(?i)^(gif|png|jpe?g|svg|webp)$"
    Html: "(?i)^(htm|html)$"
    Office: "(?i)^(docx?|xlsx?|pptx?|pps|potx?)$"
    Docs: "(?i)^(docx?|xlsx?|pptx?|pps|potx?|rtf|ods|odt|pages|ai|dxf|ttf|tiff?|wmf|e?ps)$"
    Text: "(?i)^(txt|md|csv|nfo|ini|json|php|js|css|ts|sql)$"
    Video: "(?i)^(og?|ogg|mp4|webm|mp?g|mov|3gp)$"
    Audio: "(?i)^(og?|ogg|mp3|mp?g|wav)$"
    Pdf: "(?i)^(pdf)$"
    Flash: "(?i)^(swf)$"

  # 上传文件名最长字符
  NameMaxlen: 150

